baseURL = 'http://guidebook.hdyar.com/'
languageCode = 'en-us'
title = 'The Guidebook'
theme = 'guidebook'
BookComments = false
publishDir = 'docs'
disableKinds = ['taxonomy', 'term']

[outputFormats.Moved]
MediaType = "application/json"
BaseName = "moved"
IsHTML = false
IsPlainText = true
notAlternative = true

[outputs]
home = ["HTML", "RSS", "JSON", "moved"]

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'dracula'
    tabWidth = 4

[markup.goldmark.renderer]
  unsafe= true

